// ---------------------------------------------------------------------------
// GitLabPublisher — formats verified findings as GitLab inline discussions
// and a top-level summary note on the MR.
// ---------------------------------------------------------------------------

import type { Finding } from "../agents/state";
import type { GitLabClient } from "../gitlab-client/client";
import type { DiffFile, Discussion } from "../gitlab-client/types";
import { getLogger } from "../logger";

const logger = getLogger(["gandalf", "publisher"]);

// ---------------------------------------------------------------------------
// Formatting helpers — exported so they can be unit-tested without a client
// ---------------------------------------------------------------------------

const RISK_EMOJI: Record<Finding["riskLevel"], string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
};

const VERDICT_BADGE: Record<string, string> = {
  APPROVE: "✅ APPROVE",
  REQUEST_CHANGES: "⚠️ REQUEST CHANGES",
  NEEDS_DISCUSSION: "💬 NEEDS DISCUSSION",
};

const FINDING_MARKER_PREFIX = "<!-- git-gandalf:finding ";
const SUMMARY_MARKER = "<!-- git-gandalf:summary -->";

function buildFindingMarker(finding: Finding): string {
  return `${FINDING_MARKER_PREFIX}${finding.file}:${finding.lineStart}-${finding.lineEnd}:${finding.riskLevel}:${finding.title} -->`;
}

function buildPublishableLineMap(diffFiles: DiffFile[]): Map<string, Set<number>> {
  const publishableLines = new Map<string, Set<number>>();

  for (const diffFile of diffFiles) {
    if (diffFile.deletedFile) {
      continue;
    }

    let currentNewLine = 0;
    const lines = diffFile.diff.split("\n");
    const publishable = new Set<number>();

    for (const line of lines) {
      if (line.startsWith("@@")) {
        const match = /@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/.exec(line);
        if (match) {
          currentNewLine = Number(match[1]);
        }
        continue;
      }

      if (line.startsWith("+++") || line.startsWith("---") || line.length === 0) {
        continue;
      }

      if (line.startsWith("+")) {
        publishable.add(currentNewLine);
        currentNewLine++;
        continue;
      }

      if (line.startsWith("-")) {
        continue;
      }

      currentNewLine++;
    }

    publishableLines.set(diffFile.newPath, publishable);
  }

  return publishableLines;
}

function resolveInlineLine(finding: Finding, publishableLines: Map<string, Set<number>>): number | null {
  const candidateLines = publishableLines.get(finding.file);
  if (!candidateLines) {
    return null;
  }

  for (let lineNumber = finding.lineStart; lineNumber <= finding.lineEnd; lineNumber++) {
    if (candidateLines.has(lineNumber)) {
      return lineNumber;
    }
  }

  return null;
}

function buildSuggestionFenceHeader(finding: Finding, anchorLine: number): string {
  const linesAbove = Math.max(anchorLine - finding.lineStart, 0);
  const linesBelow = Math.max(finding.lineEnd - anchorLine, 0);
  return `\`\`\`suggestion:-${linesAbove}+${linesBelow}`;
}

export function formatFindingComment(finding: Finding, anchorLine = finding.lineStart): string {
  const emoji = RISK_EMOJI[finding.riskLevel];
  const lines = [
    buildFindingMarker(finding),
    `## ${emoji} ${finding.riskLevel.toUpperCase()}: ${finding.title}`,
    "",
    `**Risk**: ${finding.description}`,
    "",
    `**Evidence**: ${finding.evidence}`,
  ];

  if (finding.suggestedFix) {
    lines.push("", `**Suggested Fix**: ${finding.suggestedFix}`);
    if (finding.suggestedFixCode !== undefined) {
      lines.push(buildSuggestionFenceHeader(finding, anchorLine), finding.suggestedFixCode, "```");
    }
  }

  return lines.join("\n");
}

export function formatSummaryComment(verdict: string, findings: Finding[]): string {
  const badge = VERDICT_BADGE[verdict] ?? verdict;
  const counts: Record<Finding["riskLevel"], number> = { critical: 0, high: 0, medium: 0, low: 0 };

  for (const f of findings) counts[f.riskLevel]++;

  const lines = [
    SUMMARY_MARKER,
    `## 🤖 GitGandalf Code Review — ${badge}`,
    "",
    "### Summary",
    "",
    "| Severity | Count |",
    "|---|---|",
    `| 🔴 Critical | ${counts.critical} |`,
    `| 🟠 High | ${counts.high} |`,
    `| 🟡 Medium | ${counts.medium} |`,
    `| 🔵 Low | ${counts.low} |`,
  ];

  if (findings.length === 0) {
    lines.push("", "_No findings — code looks good!_");
  } else {
    lines.push("", "### Findings", "");
    for (const f of findings) {
      const emoji = RISK_EMOJI[f.riskLevel];
      lines.push(`- ${emoji} **${f.title}** (\`${f.file}:${f.lineStart}-${f.lineEnd}\`)`);
    }
  }

  lines.push("", "---", "_Review generated by [GitGandalf](https://github.com/elis-salobehaj/git-gandalf)_");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// GitLabPublisher
// ---------------------------------------------------------------------------

export class GitLabPublisher {
  constructor(private gitlab: GitLabClient) {}

  /**
   * Post each verified finding as an inline discussion on the MR diff.
   * Skips findings that already have a matching discussion to avoid duplicates.
   */
  async postInlineComments(
    projectId: number,
    mrIid: number,
    findings: Finding[],
    diffRefs: { baseSha: string; headSha: string; startSha: string },
    diffFiles: DiffFile[],
  ): Promise<void> {
    if (findings.length === 0) return;

    const existing = await this.gitlab.getMRDiscussions(projectId, mrIid);
    const publishableLines = buildPublishableLineMap(diffFiles);

    for (const finding of findings) {
      const inlineLine = resolveInlineLine(finding, publishableLines);
      if (inlineLine === null) {
        logger.warn("Skipping non-diff finding", {
          title: finding.title,
          file: finding.file,
          lineStart: finding.lineStart,
          lineEnd: finding.lineEnd,
        });
        continue;
      }

      if (this.isDuplicate(finding, existing)) {
        logger.debug("Skipping duplicate finding", {
          title: finding.title,
          file: finding.file,
          lineStart: finding.lineStart,
        });
        continue;
      }

      try {
        await this.gitlab.createInlineDiscussion(projectId, mrIid, formatFindingComment(finding, inlineLine), {
          baseSha: diffRefs.baseSha,
          startSha: diffRefs.startSha,
          headSha: diffRefs.headSha,
          newPath: finding.file,
          newLine: inlineLine,
        });
      } catch (error) {
        logger.error("Failed to post finding", {
          title: finding.title,
          error: error instanceof Error ? error.message : String(error),
        });
      }
    }
  }

  /**
   * Post a top-level MR note summarising the review verdict and all findings.
   */
  async postSummaryComment(projectId: number, mrIid: number, verdict: string, findings: Finding[]): Promise<void> {
    await this.gitlab.createMRNote(projectId, mrIid, formatSummaryComment(verdict, findings));
  }

  /**
   * Returns true if any existing discussion already covers the finding's
   * file + line range, indicating it was posted in a prior run.
   */
  private isDuplicate(finding: Finding, existing: Discussion[]): boolean {
    const marker = buildFindingMarker(finding);

    return existing.some((d) =>
      d.notes.some(
        (n) =>
          n.body.includes(marker) &&
          n.position?.newPath === finding.file &&
          n.position.newLine !== null &&
          n.position.newLine !== undefined &&
          n.position.newLine >= finding.lineStart &&
          n.position.newLine <= finding.lineEnd,
      ),
    );
  }
}
